---

name: Build Image
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2.3.4
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2.3.4
      with:
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: |
        cd repository/src/image
        wget -c --trust-server-names 'https://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.xz'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths

    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x ./build_dist

    - name: Copy output
      # if: github.event_name == 'schedule'
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-farmpi-$DIST_VERSION

        cp repository/src/workspace/*.img $IMAGE.img

        echo "::set-output name=image::$IMAGE"

    - name: Zip Image
      # if: github.event_name == 'schedule'
      run: |
        mkdir deploy
        zip deploy/${{ steps.copy.outputs.image }}.zip ${{ steps.copy.outputs.image }}.img

    - name: Upload to server
      # if: github.event_name == 'schedule'
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: '${{ secrets.SSH_USERNAME }}'
        server: '${{ secrets.SSH_REMOTE_HOST }}'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './deploy/'
        remote_path: /web/farmpi.octofarm.net/public_html/nightly'
        args: '-o ConnectTimeout=5'
